### ISSUE TITLE
Change Elo

### ISSUE THREAD

**Issue by dan4112** [Xyrus2000/ChessBridge#1]
Hi, I'd like to be able to use your program to change the elo ratings of the personalities. Can you tell me how to do that or work it into your program?

**Comment by Xyrus2000** [comment]
It's been quite a while since I looked at this code. :)

Unfortunately, there is no direct way to set the ELO of a personality. You can override the the ELO number in the metadata but that has no impact on the engine. The performance of the personality is based on the parameters of the personality, and there's no mathematical formula I'm aware of that can translate those personality traits into an ELO rating.

You could, however, create personalities and run them against an engine that does have such an explicit engine setting in a tournament. For example you could set up The King to run your personality against different levels of StockFish using Arena or something.
